### PR TITLE
cpt

### PR DESCRIPTION
**Pull request by matklad**
- mktemp_d and tests for cp
- Publish 0.1.7

### CODE REVIEW

**Comment by azdavis** [comment]
I am on macOS, and I took a look.

Seems like running just  `test_pushenv` and `test_cp` (disabling all other tests) sometimes triggers the deadlock. I investigated in https://github.com/azdavis/xshell/commits/master .

A minimal deadlocking test seems to be https://github.com/azdavis/xshell/commit/410794f823f857f89f65222b55d44af1b106841a . I can't see why this would deadlock though. The test does this:

- It acquires the read lock
- Then tries to acquire the write lock but blocks since we still have a read guard as expected
- Then tries to acquire another read guard, which should work, but instead hangs

**Comment by matklad** [comment]
You are my hero @azdavis ! I think this explains the behavior! When implementing a RW lock, one problem to keep in mind is writer's starvation. 

If many readers repeatedly read lock and unlock the rw lock, a writer may block indefinitely. For this reason, usually, as long as writer tries to grap a lock, all further attempts of readers to lock will block. So after some time, old readers release their locks, the writer does its job, and the new readers are unlocked. 

It seems like linux and windows either don't protect against starvation, or special case recursive locking by the same  thread.

**Comment by matklad** [comment]
@azdavis are you perhaps interested in fixing this? I think just making your unit test work will do the trick. I think it might be enough to extend the logic in https://github.com/azdavis/xshell/blob/410794f823f857f89f65222b55d44af1b106841a/src/gsl.rs#L44-L46 to cache both read and write lock (currently the bool represents write lock).

**Comment by azdavis** [comment]
I took a look in #16 :D

**Pull request closed without merging**
