### PR TITLE
fix: allow panics to transparently pass through xshell code

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Review by azdavis — APPROVED** [review]
nice. i’m not super familiar with lock/poisoning: i “know” what it is but it’s good to have an example that would fail if we didn’t ignore the poisoning errors with `into_inner`. especially since i changed it to unwrap earlier 😅

**Comment by matklad** [comment]
Yeah. The more I look at gsl, the more I dislike the whole concoction... If only we had format strings in Rust, I think we could go with the following API:

```rust 
let shell = xshell::new();
shell.cd("./some/dir");
shell.run(f"git switch {branch_name}")?;
```

but 

```rust
shell.run(cmd!("git switch {branch_name}"))?;
```

doesn't feel nearly as nice.

**Pull request merged**
