### PR TITLE
Add environment manipulation functions to xshell::cmd

### PR DESCRIPTION
**Pull request by thomcc**
This is one of those cases where the tests are way trickier than the code.

I think I know how to better test #19 too now, so I'll try to get back to that sooner rather than later.

### CODE REVIEW

**Comment by matklad** [comment]
we use 1.47 as MSRV, so the test code needs to be adjusted.

**Comment by matklad** [comment]
I'll fix this up myself

**Comment by thomcc** [comment]
> we use 1.47 as MSRV, so the test code needs to be adjusted.

My bad! Thanks for fixing it up

**Pull request merged**
